<?php
// $Id$

/**
 * @file
 * This module allows users to import their personal information from Facebook.
 */
 
define('FBCONNECT_USER_CACHE_EXPIRE', 24);
 
/**
 * Implementation of hook_menu().
 */
function fbconnect_profile_menu() {  
  $items['fbconnect/register/import'] = array(
    'page callback' => 'fbconnect_profile_import_page',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_is_anonymous',
  );
  return $items;
}

/**
 * This function build the user import page.
 */
function fbconnect_profile_import_page() {
  if ($fbuid = fbconnect_get_fbuid()) {
    drupal_set_title(t('Import your profile information from Facebook'));
    $output  = fbconnect_render_avatar($fbuid);
    $output .= drupal_get_form('fbconnect_profile_import_form');
    return $output;
  }
}

/**
 * Return the import form.
 */
function fbconnect_profile_import_form() {
  $form['imp'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );
  $fbuid  = fbconnect_get_fbuid();
  $form['imp']['field_import'] = array(
    '#type' => 'checkboxes',
    '#options' => fbconnect_profile_available_import($fbuid),
    '#default_value' => variable_get('fbconnect_profile_fields', NULL),
    '#description' => t('Select the public Facebook profile information you wish to import.
      This information will be displayed on your public profile.'),
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Next'),
  );
  return $form;
}

/**
 * import_form() validate function.
 */
function fbconnect_profile_import_form_validate($form, &$form_state) {
  if ($fields = array_filter((array)$form_state['values']['field_import'], 'fbconnect_import_filter')) {
   $_SESSION['fb_reg_import'] = $fields;
  }
}

function fbconnect_profile_import_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'fbconnect/register/create';  
}

/**
 * Validate user information available from facebook
 *
 * @return array
 */
function fbconnect_profile_available_import($fbuid) {
  $conf = variable_get('fbconnect_profile_fields', NULL);
  $fields = implode(', ', array_filter($conf, 'fbconnect_import_filter'));
  
  if ($res = fbconnect_get_info_from_fb($fbuid, $fields )) {
    $label = variable_get('facebook_user_fields', NULL);
    foreach ($res as $key => $value) {
      if ($value) {
        if (is_array($value)) {
          $field[$key] .= $label[$key];        
        }
        else {
          $field[$key] .= $label[$key] .' : '. check_plain($value);
        }
      }
    }
    return $field;
  }
}
 
/**
 * Implementation of hook_form_alter().
 */
function fbconnect_profile_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'fbconnect_admin_settings') {
    $form['import'] = array(
      '#type' => 'fieldset',
      '#title' => t('Facebook profile settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#weight' => -1,
    );
      
    $form['import']['fbconnect_profile_fields'] = array(
      '#type' => 'checkboxes',
      '#options' => variable_get('facebook_user_fields', NULL),
      '#default_value' => variable_get('fbconnect_profile_fields', array_keys(variable_get('facebook_user_fields', NULL))),
    );
  }
  if ($form_id == 'fbconnect_user_settings_form') {
    if ($fbuid = fbconnect_get_fbuid()) {
      $form['import'] = array(
        '#type' => 'fieldset',
        '#collapsible' => FALSE,
        '#weight' => -1,
      );
      
      $user    = user_load(array('uid' => arg(1)));
      $default = fbconnect_profile_get_user_import_setting($user);
      $options = fbconnect_profile_available_import($fbuid);
    
      $form['import']['import_setting'] = array(
        '#type' => 'checkboxes',
        '#description' => t('This information is displayed on my profile.'),
        '#options' => $options,
        '#default_value' => (array)$default,
      );
      
      $form['#submit'][] = 'fbconnect_profile_user_settings_submit';      
    }
  }
}

function fbconnect_profile_user_settings_submit($form, &$form_state) {
  $user = user_load(array('uid' => arg(1)));
  $conf = $form_state['values']['import_setting'];
  
  if ($fields = array_filter((array)$conf, 'fbconnect_import_filter')) {
    fbconnect_profile_insert_user_info($user, $fields);
  }
  else {
    db_query("UPDATE {fbconnect_users} SET import_setting = '' WHERE uid = %d", $user->uid);
    db_query('DELETE FROM {fbconnect_profile} WHERE uid = %d', $user->uid);
  }
}


/**
 * Implementation of hook_user().
 */
function fbconnect_profile_user($op, &$edit, &$account, $category = NULL) {
  switch($op) {
    case 'view':
      $account->content['fbconnect']['profile'] = array(
        '#type' => 'user_profile_item',
        '#value' => theme('fb_user_profile', fbconnect_profile_get_profile($account->uid), $account),
        '#weight' => 0,
      );
    break;
  }
}

/**
 * Implementation of hook_theme().
 */
function fbconnect_profile_theme() {
  return array(
    'fb_user_profile' => array(
      'arguments' => array('data' => NULL, 'account' => NULL)
    )
  );
}

/**
 * Return themed user profile
 *
 * @param array $data
 *   An array containing the data to display
 * @param object $account
 *   Drupal user object
 * @return formated HTML
 */
function theme_fb_user_profile($data, $account) {
 if (!empty($data) && !empty($account)) {
    $label = variable_get('facebook_user_fields', '');
    foreach ($data as $key => $value) {
      if (is_array($value)) {
        switch ($key) {
          case 'affiliations':
            $output .= '<dt>'. $label[$key] .': </dt><dd>'. $value[0]['name'] .'</dd>';
          break;                  
          case 'hometown_location':
            $output .= '<dt>'. $label[$key] .': </dt><dd>'. $value['city'] .', '. $value['state'] .', '. $value['country'] .'</dd>';
          break;
        }
      }
      else {
        $output .= '<dt>'. $label[$key] .': </dt><dd>'. $value .'</dd>';
      }
    }
    return '<dl class="facebook_info">'. $output .'</dl><div class="clear"></div>';
  }
}

/**
 * Query fbconnect user information.
 *
 * @return array
 */
function fbconnect_profile_get_profile($uid) {
  $result = db_fetch_array(db_query('SELECT * FROM {fbconnect_profile} WHERE uid = %d', $uid));              
  if ($result) {
    $serialized = array('affiliations', 'hometown_location', 'current_location', 'meeting_sex', 'meeting_for');    
    $data = array();
    foreach ($result as $key => $value) {
      if ($key == 'uid') {
        continue;
      }
      else if (in_array($key, $serialized) && $value) {
        $data[$key] = unserialize($value);
      }
      else if ($value) {
        $data[$key] = $value; 
      }
    }
    return $data;
  }
}

/**
 * Implementation of hook_cron().
 */
function fbconnect_profile_cron() {
  $expire = time() - FBCONNECT_USER_CACHE_EXPIRE * 3600;
  $query = 'DELETE {fbconnect_profile} FROM {fbconnect_profile} INNER JOIN {fbconnect_users}
            WHERE {fbconnect_users}.uid = {fbconnect_profile}.uid 
            AND timestamp < %d';
  db_query($query, $expire);
}

/**
 * Recupere les parametres d'importation de l'utilisateur
 */
function fbconnect_profile_get_user_import_setting($user) {
  $data = db_result(db_query('SELECT import_setting FROM {fbconnect_users} WHERE uid = %d', $user->uid));
  if ($data != NULL) {
     return unserialize($data);
  }
}

/**
 * Enregistre les informations du profile facebook.
 *
 * @param Object $user
 *   Drupal user object
 * @param Array $fields_setting
 */
function fbconnect_profile_insert_user_info($user, $fields_setting) {
  $fbuid = fbconnect_get_fbuid();  
  $fb_user_profile = fbconnect_get_info_from_fb($fbuid, implode(',', $fields_setting));
  
  if (count($fields_setting) != count($fb_user_profile)) {
    watchdog('fbconnect', 'Error importing from facebook for fbuid : %fbuid', array('%fbuid' => $fbuid));
    drupal_set_message(t('Error importing from facebook'), 'error');    
    return;               
  }
  // Drupal uid
  $fields[] = 'uid';
  $values[] = $user->uid;
  $s[] = "%d";
  
  foreach ($fb_user_profile as $key => $value) {
    $fields[] = $key;
    $values[] = (is_array($value)) ? serialize($value) : $value;
    $s[] = "'%s'";
  }
  // Save user information imported from Facebook 
  db_query('REPLACE INTO {fbconnect_profile} ('. implode(', ', $fields) .') VALUES ('. implode(', ', $s) .')', $values);
  // Update the 24h cache timer and save fields settings.
  db_query("UPDATE {fbconnect_users} SET timestamp = %d, import_setting = '%s' WHERE uid = %d", time(), serialize($fields_setting), $user->uid);
}
