<?php

/**
 * Implemetation of hook_fbconnect_config_alter().
 * @param array $config
 */
function fbconnect_fb_social_fbconnect_config_alter(&$config) {
  $config['app_id'] = variable_get('fb_social_appid', '');
  $config['language_code'] = variable_get('fb_social_locale', 'en_US');
  $config['debug'] = FALSE;
  $config['omit_fb_init_code'] = TRUE;
}

/**
 * Impletementation of hook_form_alter().
 */
function fbconnect_fb_social_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'fbconnect_api_keys_settings') {
    $form['fbconnect_appid']['#disabled'] = TRUE;
    $form['fbconnect_appid']['#required'] = FALSE;
    $form['fbconnect_appid']['#value'] = variable_get('fb_social_appid', '');
    $form['fbconnect_appid']['#description'] = t('You can change App ID on !link', array(
      '!link' => l(t('fb_social module settings page'), 'admin/settings/fb/social'),
    ));
    
    $form['fbconnect_debug']['#disabled'] = TRUE;
    $form['fbconnect_language_code']['#disabled'] = TRUE;
    
    $form['fbconnect_skey']['#weight'] = -1;
  }  
}